### ISSUE TITLE
I want to scan two pages at once

### ISSUE THREAD

**Issue by ankitkumarsewak** [jordan-jakisa/pdf_creator#1]

**Comment by jordan-jakisa** [comment]
I think the best option for that is to scan with your phone in landscape mode such that both pages are captured at once.

Like shown in this image
![Screenshot_20241213-143225](https://github.com/user-attachments/assets/c3328d05-222b-47f6-b753-b90cc6d06d48)

**Comment by ankitkumarsewak** [comment]
i need this concept during two page scanning with two floating  rectangle.  

![Image](https://github.com/user-attachments/assets/181bc42b-7ef7-435e-9fe3-40bc99931424)

**Comment by ankitkumarsewak** [comment]
any update?
